config/routes.rb
# -*- encoding : utf-8 -*-
FbappToplikedstatus::Application.routes.draw do

  match '/auth/:provider/callback' => 'sessions#create'
  match '/auth/:provider' => 'sessions#setup'
  match '/auth/failure' => 'sessions#failure'
  match '/logout' => 'sessions#destroy', :as => :logout

  match  '/facebookapp' => 'facebook_app#create', :as => :app

  root :to => 'home#index'

end

app/models/facebook_status.rb
class FacebookStatus < ActiveRecord::Base

  class << self

    def updated_statuses(graph_details)
      @graph_details = graph_details
      begin
        fb_user = @graph_details.get_object("me")
        #statuses = @graph_details.fql_query("SELECT post_id,likes.count,created_time, message FROM stream WHERE type = '46' AND source_id = #{fb_user["id"]}  LIMIT 25 OFFSET 10")
        statuses = @graph_details.get_connection(fb_user["id"], "statuses", :since =>'2011-12-31T23:59:59+0000',:until =>'2012-12-31T23:59:59+0000' )

        status_array = Array.new
        status_array.push(statuses)

        while !statuses.next_page_params.nil?
          statuses = statuses.next_page
          status_array.push(statuses)
        end

        formated_status = Hash.new

        for status in status_array[0]
          formated_status[status["message"]] = counted_likes(status["id"]),status["updated_time"]
        end

        result = formated_status.sort {|a1,a2| a2[1]<=>a1[1]}

        if result.length > 0
          result =result.first()
          toplikedstatus = "My Most Liked Status of 2012 #{"\n"} Status: #{result[0]}, No of Likes #{result[1][0]} #{"\n"} updated on #{formated_time(result[1][1])}"
          wall_post(toplikedstatus)
          return toplikedstatus
        end

      rescue => e
          raise e
          Rails.logger.info e
      end
    end

    def counted_likes(object_id)
      user_likes = @graph_details.fql_query("SELECT user_id from like WHERE object_id = #{object_id}")
      return user_likes.length
    end

    def formated_time(time)
      Time.parse(time).strftime("%y/%m/%d")
    end

    def wall_post(toplikedstatus)
      @graph_details.put_wall_post(toplikedstatus.to_s)
    end

  end
end

app/models/user.rb
class User < ActiveRecord::Base

  scope :authenticated, where("access_token IS NOT NULL AND access_token != ''")

  class << self

    def authenticate(auth)
      begin
        create! do |user|
          user.provider = auth["provider"]  
          user.uid = auth["uid"]  
          user.access_token = auth["credentials"]["token"]
          user.email = auth["info"]["email"]
          user.name = auth["info"]["name"]
          user.save! 
        end
      rescue Exception => e
        raise e, "cannot create user record"  
      end
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  #protect_from_forgery

  helper_method :current_user, :logged_in?
  around_filter :access_log


  private

  def current_user
    @current_user ||= User.authenticated.find_by_access_token!(cookies[:access_token])
  rescue ActiveRecord::RecordNotFound
    cookies[:access_token] = nil
  end

  def logged_in?
    !!current_user
  end

  def require_login
    unless logged_in?
      respond_to do |format|
        format.html do
          session[:return_to] = request.path
          redirect_to '/auth/facebook?redirect_back=yes'
        end
        format.json do
          head :unauthorized
        end
      end
    end
  end

  def access_log
    request_time = Time.now

    e_status  = nil
    e_message = nil
    e_body    = nil

    begin
      yield
    rescue
      e = $!

      e_message = e_body = "#{e.inspect}"

      if e.respond_to?(:response) and e.response
        e_status = e.response.code if e.response.respond_to?(:code)
        if e.response.respond_to?(:read_body)
          e_body += "#{e.response.read_body.gsub("\n","")}"
          logger.debug e.response
        end
      else
        e_status = "500"
      end

      begin
        unless e_status.to_i == 404
          AlertMailer.error(e, { fullpath: request.original_fullpath })
        end
      rescue
        logger.error("Failed to send alert mail: #{$!}")
      end

      raise

    ensure
      request_method   = request.request_method      || '-'
      request_protocol = request.server_protocol     || '-'
      response_time    = ((Time.now - request_time)*1000).round
      response_status  = e_status || response.status || '-'
      location         = response.location           || '-'
      remote_addr      = request.remote_ip           || '-'
      path             = request.original_fullpath   || '-'
      referer          = request.referer             || '-'
      user_agent       = request.user_agent          || '-'

      logger.info %([access] #{remote_addr} #{response_time}ms "#{request_method} #{path} #{request_protocol}" #{response_status} #{location} "#{referer}" "#{user_agent}")

    end
  end

#error handling

rescue_from Koala::Facebook::APIError, :with => :handle_fb_exception

private
  def handle_fb_exception exception
    if exception.fb_error_type.eql? 'OAuthException'
        redirect_to root_url
    else
      logger.debug "bug in Koala gem; reraising the exception..."
      raise exception
    end
  end
end

app/controllers/facebook_app_controller.rb
class FacebookAppController < ApplicationController
  before_filter :require_login, :only => [:create]
  before_filter :graph_details

  layout 'facebook_app'

  def create
    begin
      @toplikedstatus = FacebookStatus.updated_statuses(graph_details)
      Rails.logger.info @toplikedstatus
    rescue => e
        raise e
    end
  end

private
  def graph_details
    if current_user
      @graph_details ||= Koala::Facebook::API.new(cookies["access_token"])
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'home'
  
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create  
    auth = request.env["omniauth.auth"]
    user = User.authenticate(auth)
    cookies[:access_token] = user.access_token if user
    redirect_to session.delete(:return_to) || root_url
  end

  def setup
    session[:return_to] = request.referer if params[:redirect_back]
    render :text => "Setup complete.", :status => 404
  end

  def destroy
    cookies[:access_token] = nil
    redirect_to root_url
  end

  def failure
    redirect_to root_url
  end
 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/facebook_app_helper.rb
module FacebookAppHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/facebook_app/create.html.erb
<h1> Thank you very much for using this app </h1>
<br>
<h3>Your Top Liked status has been publish on your facebook wall </h3>
<h4>This is the published status</h4>
<%= @toplikedstatus %>
<br>
<br>
<br>

app/views/home/index.html.erb
<% content_for :meta do %>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>Welcome to TopMostLikedStatus FaceBook APP</title>
<meta name="description" content="">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="Content-Style-Type" content="text/css">
<meta http-equiv="Content-Script-Type" content="text/javascript">
<%= favicon_link_tag "/favicon.ico",:rel =>"shortcut icon", :type => nil, :media => nil %>
<%= stylesheet_link_tag "application.css" , :rel => "stylesheet", :type => nil, :media => nil %>
<%end%>    

<h1>Welcome to TopMostLikedStatus APP</h1>
<br>
<br>
<input type=button onClick="location.href='/facebookapp'" value='Connect with FaceBook'>
          <iframe src="//www.facebook.com/plugins/like.php?href=<%= u app_url%>&amp;send=false&amp;layout=button_count&amp;width=450&amp;show_faces=true&amp;action=like&amp;colorscheme=light&amp;font&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:105px; height:21px;" allowTransparency="true"></iframe>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Likedphotos</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/facebook_app.html.erb
<!DOCTYPE HTML>
<html lang="en">
  <head>
    <%= yield :meta -%>
  </head>
  <body>
    <div id="mypage">
      <%= yield %>
    </div>
<div class="fb-like" data-href="https://apps.facebook.com/topmostlikedstatus/" data-send="true" data-width="450" data-show-faces="true"></div>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=468010193256112";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE HTML>
<html lang="en">
  <head>
    <%= yield :meta -%>
  </head>
  <body>
    <div id="mypage">
      <%= yield %>
    </div>
  </body>
</html>